-- Crear el usuario
CREATE USER PROYECTO_PARQUEO IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- Dar privilegios básicos
GRANT CONNECT, RESOURCE TO PROYECTO_PARQUEO;

-- (Opcional) Permitir crear procedimientos
GRANT CREATE PROCEDURE TO PROYECTO_PARQUEO;
GRANT CREATE SEQUENCE TO PROYECTO_PARQUEO;
GRANT CREATE TRIGGER TO PROYECTO_PARQUEO;
GRANT CREATE VIEW TO PROYECTO_PARQUEO;

ALTER USER PROYECTO_PARQUEO IDENTIFIED BY parqueo123;

ALTER USER PROYECTO_PARQUEO ACCOUNT UNLOCK;
ALTER USER PROYECTO_PARQUEO IDENTIFIED BY parqueo123;

GRANT CREATE SESSION TO PROYECTO_PARQUEO;

CREATE USER PROYECTO_PARQUEO IDENTIFIED BY parqueo123;

-- Dale los privilegios necesarios
GRANT CREATE SESSION TO PROYECTO_PARQUEO;
GRANT CREATE TABLE TO PROYECTO_PARQUEO;
GRANT CREATE SEQUENCE TO PROYECTO_PARQUEO;
GRANT CREATE PROCEDURE TO PROYECTO_PARQUEO;
GRANT CREATE TRIGGER TO PROYECTO_PARQUEO;
GRANT UNLIMITED TABLESPACE TO PROYECTO_PARQUEO;


-- Cambiar al contenedor correcto (solo si estás en la CDB)
ALTER SESSION SET CONTAINER = XEPDB1;

-- Crear el usuario
CREATE USER PROYECTO_PARQUEO IDENTIFIED BY parqueo123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- Otorgar permisos básicos para conectarse y trabajar
GRANT CREATE SESSION TO PROYECTO_PARQUEO;
GRANT CREATE TABLE TO PROYECTO_PARQUEO;
GRANT CREATE SEQUENCE TO PROYECTO_PARQUEO;
GRANT CREATE VIEW TO PROYECTO_PARQUEO;
GRANT CREATE PROCEDURE TO PROYECTO_PARQUEO;
GRANT CREATE TRIGGER TO PROYECTO_PARQUEO;
GRANT CREATE SYNONYM TO PROYECTO_PARQUEO;
GRANT UNLIMITED TABLESPACE TO PROYECTO_PARQUEO;

-- (Opcional pero útil para desarrollo)
GRANT SELECT ANY TABLE TO PROYECTO_PARQUEO;

SELECT username, account_status FROM dba_users WHERE username = 'PROYECTO_PARQUEO';
